// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tdxBvH2PqYqj7Lh7ivXHnR

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi"; // plasmic-import: Nz3wPi974V7/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, strapiCredentialsProviderProps } = props;

  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host!
          : ("https://0306-212-112-111-65.ngrok-free.app" as const)
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token!
          : ("079c524e3d3147acc3f222b427a57ae9c65c5269a7fa34e5254b0aea5cda83b7b7410faf227ab40e708eb8aa5507260327ab0a2d795b9ec8d8366bb134567595f61233ba145bc7590affbad17146f3e0c411e7ed101c7269d9aecf030aee1b706e08c49b3c0ef226533750d21bbe6e80e412317fb87f98198b8d54ce6da8781b" as const)
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
